application:
  port: 8000
database:
  host: "localhost"
  port: 55000
  username: "postgres"
  password: "postgrespw"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "HhMO.WQ3FL_whs"
  timeout_milliseconds: 10000